# Note: Remove the baseurl in order to deploy at the domain root
# baseurl: /jekyll-theme-tufte
domain: nycpact.github.io
url: https://nycpact.github.io
title: NYC PACT
# Whether the header (with large title and subtitle) should be displayed
header: false
# subtitle: A Jekyll theme based on tufte-css
author: PhDs at Cornell Tech. Equal Education and Employment.
description: Main homepage for PACT
show_author: true
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge
# permalink: /blog/:categories/:year/:month/:day/:title.html
permalink: /blog/:categories/:slug
timezone: America/New_York
excerpt_separator: <!--more-->
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']
plugins:
  - jekyll-feed
